#######################################################################################
#+-----------------------------------------------------------------------------------+#
#|                                                                                   |#
#|                             SuperCraftBros Configuration                          |#
#|                                     By: dmulloy2                                  |#
#|                                                                                   |#
#+-----------------------------------------------------------------------------------+#
#######################################################################################

# This is the main configuration file for SuperCraftBros
# It follows standard YAML procedure
# Input: boolean - true/false, String - "text", integer - number

#############################################
#+-----------------------------------------+#
#|          Global Configuration           |#
#+-----------------------------------------+#
#############################################

# Join timer
# Enabled - boolean
# Seconds - integer
joinTimer:
  enabled: true
  seconds: 2
  
#############################################
#+-----------------------------------------+#
#|                Rewards                  |#
#+-----------------------------------------+#
#############################################

# Rewards
# Enabled - booelan
# Money - integer
# Items - List<Item>
rewards:
  enabled: true
  money: 250
  items:
    - "266:0, 9"
    - "46:0, 3"

#############################################
#+-----------------------------------------+#
#|            Random Item Drops            |#
#+-----------------------------------------+#
#############################################

# Random item drops
# Enabled - boolean
# Items - List<Item>; format - "id:dat, amt"
randomItemDrops:
  enabled: true
  items:
    - "373:8257, 1"
    - "383:54, 1"
    - "383:50, 1"
    - "322:0, 1"
    - "276:1561, 1, sharp:5, knock:2, fireaspect:2"
    - "373:16452, 1"
    - "373:8227, 1"
    - "373:8261"
    - "373:8268"
    - "373:16460"
    - "267:250, 1, sharp:5, knock:2, fireaspect:2"